use_frameworks!
target 'SceneManageSample' do
pod 'Bond', :git => 'https://github.com/SwiftBond/Bond.git', :tag => 'v5.4.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings['SWIFT_VERSION'] = "3.0"
    end
  end
end